# Generated by Django 2.0.6 on 2019-06-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_teacher_groups'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='office.Group', verbose_name='Група студента'),
            preserve_default=False,
        ),
    ]
