# Generated by Django 2.0.6 on 2019-05-30 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name="Ім'я")),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Прізвище')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='По батькові')),
                ('access', models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('student', 'Student'), (None, None)], default=None, max_length=10, verbose_name='Офіс користувача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
            options={
                'verbose_name': 'Профіль',
                'verbose_name_plural': 'Профілі',
            },
        ),
    ]
