# Generated by Django 2.0.6 on 2019-05-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('none', None)], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
