# Generated by Django 2.0.6 on 2019-05-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), (None, None)], default=None, max_length=10),
        ),
    ]
