# Generated by Django 2.0.6 on 2019-05-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190515_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('student', 'Student'), (None, None)], default=None, max_length=10, verbose_name='Офіс користувача'),
        ),
    ]
