# Generated by Django 2.0.6 on 2019-05-20 09:10

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=news.models.image_folder)),
                ('alt', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, blank=True)),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок новини')),
                ('description', models.TextField(verbose_name='Опис новини')),
                ('preview_image', models.ImageField(upload_to=news.models.preview_image_folder, verbose_name='Головна картинка')),
                ('images', models.ManyToManyField(blank=True, to='news.Image', verbose_name='Додаткові картинки')),
            ],
        ),
    ]
