# Generated by Django 2.0.6 on 2019-05-30 14:03

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to=news.models.image_folder, verbose_name='Картинка')),
                ('alt', models.CharField(blank=True, max_length=50, verbose_name='Текстовий опис')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок новини')),
                ('short_description', models.TextField(blank=True, max_length=300, verbose_name='Короткий опис новини')),
                ('description', models.TextField(verbose_name='Повний опис новини')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('preview_image', models.ImageField(unique=True, upload_to=news.models.preview_image_folder, verbose_name='Головна картинка')),
                ('images', models.ManyToManyField(blank=True, to='news.Image', verbose_name='Додаткові картинки')),
            ],
        ),
    ]
