# Generated by Django 2.0.6 on 2019-05-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190531_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='pub_date',
        ),
    ]
