# Generated by Django 2.0.6 on 2019-05-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190531_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Короткий опис новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(max_length=120, verbose_name='Заголовок новини'),
        ),
    ]
