# Generated by Django 2.0.6 on 2019-06-11 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
