# Generated by Django 2.0.6 on 2019-06-11 10:50

import api2.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_teacher_groups'),
        ('api2', '0002_feedback_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=api2.models.file_folder, verbose_name='Документ')),
                ('title', models.CharField(max_length=120, verbose_name='Назва документу')),
                ('pub_date', models.DateField(blank=True, default=datetime.date.today)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.Group')),
            ],
        ),
    ]
