# Generated by Django 2.0.6 on 2019-05-30 14:03

from django.db import migrations, models
import django.db.models.deletion
import office.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=office.models.file_folder, verbose_name='Документ')),
                ('title', models.CharField(max_length=120, verbose_name='Назва документу')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файли',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4, unique=True, verbose_name='Номер групи')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL адреса')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Назва предмету')),
                ('slug', models.SlugField(max_length=120, verbose_name='URL адреса')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.Group', verbose_name='Група в якій буде викладатися')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ManyToManyField(blank=True, related_name='teachers', to='office.Files', verbose_name='Файли викладача')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Профіль викладача')),
                ('subjects', models.ManyToManyField(blank=True, to='office.Subject', verbose_name='Предмети викладача')),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
            },
        ),
        migrations.AddField(
            model_name='files',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.Subject', verbose_name='Предмет до якого буде відноситися документ'),
        ),
    ]
