# Generated by Django 2.0.6 on 2019-05-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='slug',
        ),
    ]
