# Generated by Django 2.0.6 on 2019-06-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20190530_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='office.Group', verbose_name='Групи в яких викладає викладач'),
        ),
    ]
