# Generated by Django 2.0.6 on 2019-05-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20190519_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='office.Files', verbose_name='Файли викладача'),
        ),
    ]
